## [作業重點]
使用 Sklearn 中的線性迴歸模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義

## 作業
試著使用 sklearn datasets 的其他資料集 (wine, boston, ...)，來訓練自己的線性迴歸模型。

### HINT: 注意 label 的型態，確定資料集的目標是分類還是回歸，在使用正確的模型訓練！

In [16]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

In [17]:
wine = datasets.load_wine()

In [18]:
x_train, x_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.1, random_state=4)

logreg = linear_model.LogisticRegression()

logreg.fit(x_train, y_train)

y_pred = logreg.predict(x_test)




D:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [21]:
acc = accuracy_score(y_test, y_pred)
print("Accuracy: ", acc)

Accuracy:  0.8888888888888888


In [22]:
boston = datasets.load_boston()

In [47]:
X = boston.data[: , np.newaxis, 2]

print("Data shape: ", X.shape)

for degree in range(1, 506 + 1):
    sinusoid_features = np.sin(degree * dataset)
    
x_train, x_test, y_train, y_test = train_test_split(x, boston.target, test_size=0.1, random_state=4)

Data shape:  (506, 1)


ValueError: Found input variables with inconsistent numbers of samples: [4, 506]

array([[ 2.31],
       [ 7.07],
       [ 7.07],
       [ 2.18],
       [ 2.18],
       [ 2.18],
       [ 7.87],
       [ 7.87],
       [ 7.87],
       [ 7.87],
       [ 7.87],
       [ 7.87],
       [ 7.87],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 8.14],
       [ 5.96],
       [ 5.96],
       [ 5.96],
       [ 5.96],
       [ 2.95],
       [ 2.95],
       [ 6.91],
       [ 6.91],
       [ 6.91],
       [ 6.91],
       [ 6.91],
       [ 6.91],
       [ 6.91],
       [ 6.91],
       [ 6.91],
       [ 5.64],
       [ 5.64],
       [ 5.64],
       [ 5.64],
       [ 4.  ],
       [ 1.22],
       [ 0.74],
       [ 1.32],
       [ 5.13],
       [ 5.13],
       [ 5.13],
       [ 5.13],
       [

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [4]:
for degree in range(1, sinusoid_degree + 1):
    sinusoid_features = np.sin(degree * dataset)
    

In [5]:
x=np.empty((4, 0))

In [6]:
x

array([], shape=(4, 0), dtype=float64)